export enum EstadosActividades {
  SIN_EMPEZAR = 'SIN_EMPEZAR',
  SOLICITADO = 'SOLICITADO',
  EN_PROGRESO = 'EN_PROGRESO',
  EN_REVISION = 'EN_REVISION',
  DEVUELTA = 'DEVUELTA',
  CONCLUIDA = 'CONCLUIDA',
}
