export enum Permisos {
  // Permisos para la POA
  LEER_POA = 'LEER_POA',
  CREAR_POA = 'CREAR_POA',

  GESTIONAR_SUPERVISION_POA = 'GESTIONAR_SUPERVISION_POA',
  GESTIONAR_TRABAJO_POA = 'GESTIONAR_TRABAJO_POA',

  // Permisos para las SubActividades
  GESTIONAR_TRABAJO_SUBACTIVIDADES = 'GESTIONAR_SUBACTIVIDADES',
  GESTIONAR_SUPERVISION_SUBACTIVIDADES = 'GESTIONAR_SUPERVISION_SUBACTIVIDADES',

  VER_DASHBOARD_JEFATURA = 'VER_DASHBOARD_JEFATURA',
  VER_DASHBOARD_CONTRALOR = 'VER_DASHBOARD_CONTRALOR',
}
