export enum CodigoDeViolacion{
    ESTADO_INVALIDO = 'ESTADO INVALIDO',
    ROL_INVALIDO = 'ROL INVALIDO',
    DATOS_INSUFICIENTES = 'DATOS INSUFICIENTES',
    FECHA_INVALIDA = 'FECHA INVALIDA',
    ENTIDAD_REPETIDA = 'ENTIDAD_REPETIDA'
}